repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: >-
          (?x)^(
            .*\.pb\.h$|
            .*\.pb\.cc$|
            .*\.proto$
          )$
      - id: forbid-submodules
      - id: mixed-line-ending
        exclude: >-
          (?x)^(
            .*\.pb\.h$|
            .*\.pb\.cc$|
            .*\.proto$
          )$
      - id: trailing-whitespace
        exclude: >-
          (?x)^(
            .*\.pb\.h$|
            .*\.pb\.cc$|
            .*\.proto$
          )$
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    - id: clang-format
      exclude: >-
        (?x)^(
          .*\.pb\.h$|
          .*\.pb\.cc$|
          .*\.proto$
        )$
